# Generated by Django 5.1.2 on 2024-10-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='train_name',
            field=models.CharField(default='Trainer', max_length=45),
        ),
    ]
