# Generated by Django 4.2.5 on 2024-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_remove_match_score_match_score_away_match_score_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_away',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home',
            field=models.IntegerField(),
        ),
    ]
